name: NPM Publish

on:
    push:
        branches: ['master']

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup pnpm
              uses: pnpm/action-setup@v2.3.0
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'
            - name: 'Install dependencies'
              run: pnpm run ci
              
            - name: 'Run tests'
              run: pnpm run test
            - name: 'Build packge'
              run: pnpm run build
            - run: pnpm publish --access=public --no-git-checks
              env:
                  NPM_AUTH_TOKEN: ${{secrets.npm_token}}
                  NPM_REGISTRY: https://registry.npmjs.org/
